Vagrant.configure("2") do |config|
  
  # configurazione delle tre macchine
  config.vm.box = "ubuntu/jammy64"


  # VM1 - REVERSE PROXY
  config.vm.define "proxyrev" do |proxyrev|
    proxyrev.vm.hostname = "proxyrev"

    proxyrev.vm.network "private_network", ip: "192.168.56.13"
    proxyrev.vm.network "forwarded_port", guest: 80, host: 18081
    proxyrev.vm.network "forwarded_port", guest: 443, host: 18443

    proxyrev.vm.provider "virtualbox" do |vb|
      vb.name = "vm-proxyrev"
      vb.memory = 1024
      vb.cpus = 1
    end

    proxyrev.vm.provision "shell", path: "provisioning/proxy.sh"
  end


  # VM2 - BACKEND 1
  config.vm.define "backserver1" do |b1|
    b1.vm.hostname = "backserver1"
    b1.vm.network "private_network", ip: "192.168.56.14"

    b1.vm.provider "virtualbox" do |vb|
      vb.name = "vm-backserver1"
      vb.memory = 512
      vb.cpus = 1
    end

    b1.vm.provision "shell", path: "provisioning/backend1.sh" 
  end


  # VM3 - BACKEND 2
  config.vm.define "backserver2" do |b2|
    b2.vm.hostname = "backserver2"
    b2.vm.network "private_network", ip: "192.168.56.15"

    b2.vm.provider "virtualbox" do |vb|
      vb.name = "vm-backserver2"
      vb.memory = 512
      vb.cpus = 1
    end

    b2.vm.provision "shell", path: "provisioning/backend2.sh"
  end

end
